# Generated by Django 4.2.1 on 2023-05-13 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_coupon_end_date_alter_coupon_start_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderStatus',
            new_name='OrderStatus',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 742266)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 742266)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 738277)),
        ),
        migrations.AlterField(
            model_name='feedbackrespone',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 739274)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 742266)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 740271)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 737280)),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 738277)),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 738277)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 58, 20, 741269)),
        ),
    ]
