# Generated by Django 4.2 on 2023-05-18 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 934766)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 934766)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 931739)),
        ),
        migrations.AlterField(
            model_name='feedbackrespone',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 932775)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 934766)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 932775)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 930741)),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 931739)),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 931739)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 20, 25, 10, 933768)),
        ),
    ]
