# Generated by Django 4.2 on 2023-05-13 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_coupon_end_date_alter_coupon_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orderstatus'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 78661)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 78661)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 75669)),
        ),
        migrations.AlterField(
            model_name='feedbackrespone',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 76666)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 78661)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 76666)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 74700)),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 75669)),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 75669)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 6, 15, 77663)),
        ),
    ]
