# Generated by Django 4.2 on 2023-05-17 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderitem_feedback_alter_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oder_item_id',
            new_name='order_item_id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 349299)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 349299)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 346307)),
        ),
        migrations.AlterField(
            model_name='feedbackrespone',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 346307)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 349299)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 347305)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 344313)),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 345310)),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 345310)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 54, 38, 348304)),
        ),
    ]
